### ISSUE TITLE
$ref are not defined in every level it may be defined

### ISSUE THREAD

**Issue by BlockLucas** [asyncapi/spec#406]
Issue part of #397 

$ref not defined in every level it may be defined. Check OAS specs for instance, it’s strictly defined where $ref field can be used and where it can’t, it’s not a free form inclusion to the AST. For example, there can’t be a $ref in an info object. A place where this is completely misleading is in the use of traits. The operation has an array of trait objects, but the field $ref is not there, so it can’t be referenced. It also states that the objects can be present in that array, which makes no sense the traits facet should only have refs. What would be the point of having an inline trait? Not having refs strictly defined (as OAS has) is confusing for the user.
https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#file-structure

**Comment by derberg** [comment]
>Check OAS specs for instance, it’s strictly defined where $ref field can be used and where it can’t

is it only in the spec or is it also set in the json schema too?

>The operation has an array of trait objects, but the field $ref is not there, so it can’t be referenced. 

could you point our what part of the spec you have in mind?

**Comment by SimonSAP** [comment]
We have encountered a related problem today when looking through the documentation and comparing it with what has been defined in the [JSON Schema description of the spec](https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/schema.json).

![image](https://user-images.githubusercontent.com/61972795/89878177-7b2ded80-dbc1-11ea-92a7-60541c204e63.png)

I'm not sure it is correct that `$ref` is mentioned at the same level as the other possible attributes. Usually you either have an object that ONLY contains `$ref` (this is the [Reference object](https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/schema.json#L59)) OR the object that contains all the properties, except `$ref`. In some instances this is done correctly in the JSON schema, and in Channel Item it seems to be not.

Another divergence from the documentation and the JSON Schema is that the table of Channel Item only suggest that `subscribe` can be an `Operation Object` when it really is `oneOf` Operation Object OR Reference (to an Operation Object)

**Comment by SimonSAP** [comment]
Sorry, I've just seen that my last point may have already been fixed here: https://github.com/asyncapi/asyncapi/pull/387/files 
Thanks!

**Comment by gutee** [comment]
@derberg In json schema this is defined too. Json schema strictly states that $ref can only be used where a full json schema can be defined. Not anywhere else, for example you cannot put a $ref inside a maxLenght property of a schema.
If you are talkin about [the json schema for OAS3](https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v3.0/schema.yaml), yes, it explicitly states where $refs can be defined as well as the spec, this is the common behaviour for oas-like specs.

> could you point our what part of the spec you have in mind?

[Here](https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#operation-trait-object) is the object that can't be a $ref. I can see though that a reference object has been added [here](https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#operation-object), which is great, but the OR here is a problem, as the traits facet should be only an array of references, what would be the point of having an inline trait? Look at the RAML spec, where traits have lived for several versions, they are only an array of references to the trait definition.

**Comment by BlockLucas** [comment]
Hi @derberg! just a friendly reminder in case you missed this issue, #408 & #410

**Comment by fmvilas** [comment]
I agree we should go over all the places it should be used and explicitely mention it on the human-readable spec. Would you mind opening a PR for that, @BlockLucas?

**Comment by gutee** [comment]
Hi @fmvilas! Any chance to look at the PR?

**Comment by fmvilas** [comment]
@gutee I did 3 weeks ago. I left some comments there.

**Comment by AgustinBettati** [comment]
Created a new PR taking into accounts the comments made in the previous one.

**Comment by derberg** [comment]
seems like already solved, leaving it closed
